### ISSUE TITLE
Usage of KEYS command

### ISSUE THREAD

**Issue by miccrun** [repsheet/librepsheet#26]
I was reading the redis documentation, it seems don't recommend people to use KEYS command http://redis.io/commands/keys

Is that a problem we should concern about? Especially when black/whitelist is very huge.

**Comment by abedra** [comment]
Yes and no. When the list grows in to the millions of keys it can be concerning. I haven't seen anything near that large yet. The SCAN command didn't exist when the initial code was written, but it is a better route for the future. This would lock librepsheet into Redis 2.8 or higher, but for the potential perf gains it is reasonable.

**Comment by miccrun** [comment]
OK, it makes sense, thanks for the explanation.

**Comment by abedra** [comment]
The KEYS command has been killed entirely now, resulting in an expected performance increase.
